/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Fastq implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String sequencingRunId;
    private final LocalDate sequencingRunDate;
    private final String portalRunId;
    private final String cohortId;
    private final String bucket;
    private final String key;
    private final String libraryId;
    private final String filename;
    private final String format;
    private final Long size;
    private final String storageClass;
    private final String eTag;
    private final LocalDateTime lastModifiedDate;

    public Fastq(Fastq value) {
        this.sequencingRunId = value.sequencingRunId;
        this.sequencingRunDate = value.sequencingRunDate;
        this.portalRunId = value.portalRunId;
        this.cohortId = value.cohortId;
        this.bucket = value.bucket;
        this.key = value.key;
        this.libraryId = value.libraryId;
        this.filename = value.filename;
        this.format = value.format;
        this.size = value.size;
        this.storageClass = value.storageClass;
        this.eTag = value.eTag;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public Fastq(
        String sequencingRunId,
        LocalDate sequencingRunDate,
        String portalRunId,
        String cohortId,
        String bucket,
        String key,
        String libraryId,
        String filename,
        String format,
        Long size,
        String storageClass,
        String eTag,
        LocalDateTime lastModifiedDate
    ) {
        this.sequencingRunId = sequencingRunId;
        this.sequencingRunDate = sequencingRunDate;
        this.portalRunId = portalRunId;
        this.cohortId = cohortId;
        this.bucket = bucket;
        this.key = key;
        this.libraryId = libraryId;
        this.filename = filename;
        this.format = format;
        this.size = size;
        this.storageClass = storageClass;
        this.eTag = eTag;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>mart.fastq.sequencing_run_id</code>.
     */
    public String getSequencingRunId() {
        return this.sequencingRunId;
    }

    /**
     * Getter for <code>mart.fastq.sequencing_run_date</code>.
     */
    public LocalDate getSequencingRunDate() {
        return this.sequencingRunDate;
    }

    /**
     * Getter for <code>mart.fastq.portal_run_id</code>.
     */
    public String getPortalRunId() {
        return this.portalRunId;
    }

    /**
     * Getter for <code>mart.fastq.cohort_id</code>.
     */
    public String getCohortId() {
        return this.cohortId;
    }

    /**
     * Getter for <code>mart.fastq.bucket</code>.
     */
    public String getBucket() {
        return this.bucket;
    }

    /**
     * Getter for <code>mart.fastq.key</code>.
     */
    public String getKey() {
        return this.key;
    }

    /**
     * Getter for <code>mart.fastq.library_id</code>.
     */
    public String getLibraryId() {
        return this.libraryId;
    }

    /**
     * Getter for <code>mart.fastq.filename</code>.
     */
    public String getFilename() {
        return this.filename;
    }

    /**
     * Getter for <code>mart.fastq.format</code>.
     */
    public String getFormat() {
        return this.format;
    }

    /**
     * Getter for <code>mart.fastq.size</code>.
     */
    public Long getSize() {
        return this.size;
    }

    /**
     * Getter for <code>mart.fastq.storage_class</code>.
     */
    public String getStorageClass() {
        return this.storageClass;
    }

    /**
     * Getter for <code>mart.fastq.e_tag</code>.
     */
    public String getETag() {
        return this.eTag;
    }

    /**
     * Getter for <code>mart.fastq.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Fastq other = (Fastq) obj;
        if (this.sequencingRunId == null) {
            if (other.sequencingRunId != null)
                return false;
        }
        else if (!this.sequencingRunId.equals(other.sequencingRunId))
            return false;
        if (this.sequencingRunDate == null) {
            if (other.sequencingRunDate != null)
                return false;
        }
        else if (!this.sequencingRunDate.equals(other.sequencingRunDate))
            return false;
        if (this.portalRunId == null) {
            if (other.portalRunId != null)
                return false;
        }
        else if (!this.portalRunId.equals(other.portalRunId))
            return false;
        if (this.cohortId == null) {
            if (other.cohortId != null)
                return false;
        }
        else if (!this.cohortId.equals(other.cohortId))
            return false;
        if (this.bucket == null) {
            if (other.bucket != null)
                return false;
        }
        else if (!this.bucket.equals(other.bucket))
            return false;
        if (this.key == null) {
            if (other.key != null)
                return false;
        }
        else if (!this.key.equals(other.key))
            return false;
        if (this.libraryId == null) {
            if (other.libraryId != null)
                return false;
        }
        else if (!this.libraryId.equals(other.libraryId))
            return false;
        if (this.filename == null) {
            if (other.filename != null)
                return false;
        }
        else if (!this.filename.equals(other.filename))
            return false;
        if (this.format == null) {
            if (other.format != null)
                return false;
        }
        else if (!this.format.equals(other.format))
            return false;
        if (this.size == null) {
            if (other.size != null)
                return false;
        }
        else if (!this.size.equals(other.size))
            return false;
        if (this.storageClass == null) {
            if (other.storageClass != null)
                return false;
        }
        else if (!this.storageClass.equals(other.storageClass))
            return false;
        if (this.eTag == null) {
            if (other.eTag != null)
                return false;
        }
        else if (!this.eTag.equals(other.eTag))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.sequencingRunId == null) ? 0 : this.sequencingRunId.hashCode());
        result = prime * result + ((this.sequencingRunDate == null) ? 0 : this.sequencingRunDate.hashCode());
        result = prime * result + ((this.portalRunId == null) ? 0 : this.portalRunId.hashCode());
        result = prime * result + ((this.cohortId == null) ? 0 : this.cohortId.hashCode());
        result = prime * result + ((this.bucket == null) ? 0 : this.bucket.hashCode());
        result = prime * result + ((this.key == null) ? 0 : this.key.hashCode());
        result = prime * result + ((this.libraryId == null) ? 0 : this.libraryId.hashCode());
        result = prime * result + ((this.filename == null) ? 0 : this.filename.hashCode());
        result = prime * result + ((this.format == null) ? 0 : this.format.hashCode());
        result = prime * result + ((this.size == null) ? 0 : this.size.hashCode());
        result = prime * result + ((this.storageClass == null) ? 0 : this.storageClass.hashCode());
        result = prime * result + ((this.eTag == null) ? 0 : this.eTag.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Fastq (");

        sb.append(sequencingRunId);
        sb.append(", ").append(sequencingRunDate);
        sb.append(", ").append(portalRunId);
        sb.append(", ").append(cohortId);
        sb.append(", ").append(bucket);
        sb.append(", ").append(key);
        sb.append(", ").append(libraryId);
        sb.append(", ").append(filename);
        sb.append(", ").append(format);
        sb.append(", ").append(size);
        sb.append(", ").append(storageClass);
        sb.append(", ").append(eTag);
        sb.append(", ").append(lastModifiedDate);

        sb.append(")");
        return sb.toString();
    }
}
