/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lims implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String sequencingRunId;
    private final LocalDate sequencingRunDate;
    private final String libraryId;
    private final String aliasLibraryId;
    private final String internalSubjectId;
    private final String externalSubjectId;
    private final String sampleId;
    private final String externalSampleId;
    private final String experimentId;
    private final String projectId;
    private final String ownerId;
    private final String workflow;
    private final String phenotype;
    private final String type;
    private final String assay;
    private final String quality;
    private final String source;
    private final String truseqIndex;
    private final LocalDateTime loadDatetime;

    public Lims(Lims value) {
        this.sequencingRunId = value.sequencingRunId;
        this.sequencingRunDate = value.sequencingRunDate;
        this.libraryId = value.libraryId;
        this.aliasLibraryId = value.aliasLibraryId;
        this.internalSubjectId = value.internalSubjectId;
        this.externalSubjectId = value.externalSubjectId;
        this.sampleId = value.sampleId;
        this.externalSampleId = value.externalSampleId;
        this.experimentId = value.experimentId;
        this.projectId = value.projectId;
        this.ownerId = value.ownerId;
        this.workflow = value.workflow;
        this.phenotype = value.phenotype;
        this.type = value.type;
        this.assay = value.assay;
        this.quality = value.quality;
        this.source = value.source;
        this.truseqIndex = value.truseqIndex;
        this.loadDatetime = value.loadDatetime;
    }

    public Lims(
        String sequencingRunId,
        LocalDate sequencingRunDate,
        String libraryId,
        String aliasLibraryId,
        String internalSubjectId,
        String externalSubjectId,
        String sampleId,
        String externalSampleId,
        String experimentId,
        String projectId,
        String ownerId,
        String workflow,
        String phenotype,
        String type,
        String assay,
        String quality,
        String source,
        String truseqIndex,
        LocalDateTime loadDatetime
    ) {
        this.sequencingRunId = sequencingRunId;
        this.sequencingRunDate = sequencingRunDate;
        this.libraryId = libraryId;
        this.aliasLibraryId = aliasLibraryId;
        this.internalSubjectId = internalSubjectId;
        this.externalSubjectId = externalSubjectId;
        this.sampleId = sampleId;
        this.externalSampleId = externalSampleId;
        this.experimentId = experimentId;
        this.projectId = projectId;
        this.ownerId = ownerId;
        this.workflow = workflow;
        this.phenotype = phenotype;
        this.type = type;
        this.assay = assay;
        this.quality = quality;
        this.source = source;
        this.truseqIndex = truseqIndex;
        this.loadDatetime = loadDatetime;
    }

    /**
     * Getter for <code>mart.lims.sequencing_run_id</code>.
     */
    public String getSequencingRunId() {
        return this.sequencingRunId;
    }

    /**
     * Getter for <code>mart.lims.sequencing_run_date</code>.
     */
    public LocalDate getSequencingRunDate() {
        return this.sequencingRunDate;
    }

    /**
     * Getter for <code>mart.lims.library_id</code>.
     */
    public String getLibraryId() {
        return this.libraryId;
    }

    /**
     * Getter for <code>mart.lims.alias_library_id</code>.
     */
    public String getAliasLibraryId() {
        return this.aliasLibraryId;
    }

    /**
     * Getter for <code>mart.lims.internal_subject_id</code>.
     */
    public String getInternalSubjectId() {
        return this.internalSubjectId;
    }

    /**
     * Getter for <code>mart.lims.external_subject_id</code>.
     */
    public String getExternalSubjectId() {
        return this.externalSubjectId;
    }

    /**
     * Getter for <code>mart.lims.sample_id</code>.
     */
    public String getSampleId() {
        return this.sampleId;
    }

    /**
     * Getter for <code>mart.lims.external_sample_id</code>.
     */
    public String getExternalSampleId() {
        return this.externalSampleId;
    }

    /**
     * Getter for <code>mart.lims.experiment_id</code>.
     */
    public String getExperimentId() {
        return this.experimentId;
    }

    /**
     * Getter for <code>mart.lims.project_id</code>.
     */
    public String getProjectId() {
        return this.projectId;
    }

    /**
     * Getter for <code>mart.lims.owner_id</code>.
     */
    public String getOwnerId() {
        return this.ownerId;
    }

    /**
     * Getter for <code>mart.lims.workflow</code>.
     */
    public String getWorkflow() {
        return this.workflow;
    }

    /**
     * Getter for <code>mart.lims.phenotype</code>.
     */
    public String getPhenotype() {
        return this.phenotype;
    }

    /**
     * Getter for <code>mart.lims.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Getter for <code>mart.lims.assay</code>.
     */
    public String getAssay() {
        return this.assay;
    }

    /**
     * Getter for <code>mart.lims.quality</code>.
     */
    public String getQuality() {
        return this.quality;
    }

    /**
     * Getter for <code>mart.lims.source</code>.
     */
    public String getSource() {
        return this.source;
    }

    /**
     * Getter for <code>mart.lims.truseq_index</code>.
     */
    public String getTruseqIndex() {
        return this.truseqIndex;
    }

    /**
     * Getter for <code>mart.lims.load_datetime</code>.
     */
    public LocalDateTime getLoadDatetime() {
        return this.loadDatetime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Lims other = (Lims) obj;
        if (this.sequencingRunId == null) {
            if (other.sequencingRunId != null)
                return false;
        }
        else if (!this.sequencingRunId.equals(other.sequencingRunId))
            return false;
        if (this.sequencingRunDate == null) {
            if (other.sequencingRunDate != null)
                return false;
        }
        else if (!this.sequencingRunDate.equals(other.sequencingRunDate))
            return false;
        if (this.libraryId == null) {
            if (other.libraryId != null)
                return false;
        }
        else if (!this.libraryId.equals(other.libraryId))
            return false;
        if (this.aliasLibraryId == null) {
            if (other.aliasLibraryId != null)
                return false;
        }
        else if (!this.aliasLibraryId.equals(other.aliasLibraryId))
            return false;
        if (this.internalSubjectId == null) {
            if (other.internalSubjectId != null)
                return false;
        }
        else if (!this.internalSubjectId.equals(other.internalSubjectId))
            return false;
        if (this.externalSubjectId == null) {
            if (other.externalSubjectId != null)
                return false;
        }
        else if (!this.externalSubjectId.equals(other.externalSubjectId))
            return false;
        if (this.sampleId == null) {
            if (other.sampleId != null)
                return false;
        }
        else if (!this.sampleId.equals(other.sampleId))
            return false;
        if (this.externalSampleId == null) {
            if (other.externalSampleId != null)
                return false;
        }
        else if (!this.externalSampleId.equals(other.externalSampleId))
            return false;
        if (this.experimentId == null) {
            if (other.experimentId != null)
                return false;
        }
        else if (!this.experimentId.equals(other.experimentId))
            return false;
        if (this.projectId == null) {
            if (other.projectId != null)
                return false;
        }
        else if (!this.projectId.equals(other.projectId))
            return false;
        if (this.ownerId == null) {
            if (other.ownerId != null)
                return false;
        }
        else if (!this.ownerId.equals(other.ownerId))
            return false;
        if (this.workflow == null) {
            if (other.workflow != null)
                return false;
        }
        else if (!this.workflow.equals(other.workflow))
            return false;
        if (this.phenotype == null) {
            if (other.phenotype != null)
                return false;
        }
        else if (!this.phenotype.equals(other.phenotype))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.assay == null) {
            if (other.assay != null)
                return false;
        }
        else if (!this.assay.equals(other.assay))
            return false;
        if (this.quality == null) {
            if (other.quality != null)
                return false;
        }
        else if (!this.quality.equals(other.quality))
            return false;
        if (this.source == null) {
            if (other.source != null)
                return false;
        }
        else if (!this.source.equals(other.source))
            return false;
        if (this.truseqIndex == null) {
            if (other.truseqIndex != null)
                return false;
        }
        else if (!this.truseqIndex.equals(other.truseqIndex))
            return false;
        if (this.loadDatetime == null) {
            if (other.loadDatetime != null)
                return false;
        }
        else if (!this.loadDatetime.equals(other.loadDatetime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.sequencingRunId == null) ? 0 : this.sequencingRunId.hashCode());
        result = prime * result + ((this.sequencingRunDate == null) ? 0 : this.sequencingRunDate.hashCode());
        result = prime * result + ((this.libraryId == null) ? 0 : this.libraryId.hashCode());
        result = prime * result + ((this.aliasLibraryId == null) ? 0 : this.aliasLibraryId.hashCode());
        result = prime * result + ((this.internalSubjectId == null) ? 0 : this.internalSubjectId.hashCode());
        result = prime * result + ((this.externalSubjectId == null) ? 0 : this.externalSubjectId.hashCode());
        result = prime * result + ((this.sampleId == null) ? 0 : this.sampleId.hashCode());
        result = prime * result + ((this.externalSampleId == null) ? 0 : this.externalSampleId.hashCode());
        result = prime * result + ((this.experimentId == null) ? 0 : this.experimentId.hashCode());
        result = prime * result + ((this.projectId == null) ? 0 : this.projectId.hashCode());
        result = prime * result + ((this.ownerId == null) ? 0 : this.ownerId.hashCode());
        result = prime * result + ((this.workflow == null) ? 0 : this.workflow.hashCode());
        result = prime * result + ((this.phenotype == null) ? 0 : this.phenotype.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.assay == null) ? 0 : this.assay.hashCode());
        result = prime * result + ((this.quality == null) ? 0 : this.quality.hashCode());
        result = prime * result + ((this.source == null) ? 0 : this.source.hashCode());
        result = prime * result + ((this.truseqIndex == null) ? 0 : this.truseqIndex.hashCode());
        result = prime * result + ((this.loadDatetime == null) ? 0 : this.loadDatetime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Lims (");

        sb.append(sequencingRunId);
        sb.append(", ").append(sequencingRunDate);
        sb.append(", ").append(libraryId);
        sb.append(", ").append(aliasLibraryId);
        sb.append(", ").append(internalSubjectId);
        sb.append(", ").append(externalSubjectId);
        sb.append(", ").append(sampleId);
        sb.append(", ").append(externalSampleId);
        sb.append(", ").append(experimentId);
        sb.append(", ").append(projectId);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(workflow);
        sb.append(", ").append(phenotype);
        sb.append(", ").append(type);
        sb.append(", ").append(assay);
        sb.append(", ").append(quality);
        sb.append(", ").append(source);
        sb.append(", ").append(truseqIndex);
        sb.append(", ").append(loadDatetime);

        sb.append(")");
        return sb.toString();
    }
}
