/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowOutput implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String portalRunId;
    private final String cohortId;
    private final String bucket;
    private final String prefix;
    private final Long keyCount;

    public WorkflowOutput(WorkflowOutput value) {
        this.portalRunId = value.portalRunId;
        this.cohortId = value.cohortId;
        this.bucket = value.bucket;
        this.prefix = value.prefix;
        this.keyCount = value.keyCount;
    }

    public WorkflowOutput(
        String portalRunId,
        String cohortId,
        String bucket,
        String prefix,
        Long keyCount
    ) {
        this.portalRunId = portalRunId;
        this.cohortId = cohortId;
        this.bucket = bucket;
        this.prefix = prefix;
        this.keyCount = keyCount;
    }

    /**
     * Getter for <code>mart.workflow_output.portal_run_id</code>.
     */
    public String getPortalRunId() {
        return this.portalRunId;
    }

    /**
     * Getter for <code>mart.workflow_output.cohort_id</code>.
     */
    public String getCohortId() {
        return this.cohortId;
    }

    /**
     * Getter for <code>mart.workflow_output.bucket</code>.
     */
    public String getBucket() {
        return this.bucket;
    }

    /**
     * Getter for <code>mart.workflow_output.prefix</code>.
     */
    public String getPrefix() {
        return this.prefix;
    }

    /**
     * Getter for <code>mart.workflow_output.key_count</code>.
     */
    public Long getKeyCount() {
        return this.keyCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WorkflowOutput other = (WorkflowOutput) obj;
        if (this.portalRunId == null) {
            if (other.portalRunId != null)
                return false;
        }
        else if (!this.portalRunId.equals(other.portalRunId))
            return false;
        if (this.cohortId == null) {
            if (other.cohortId != null)
                return false;
        }
        else if (!this.cohortId.equals(other.cohortId))
            return false;
        if (this.bucket == null) {
            if (other.bucket != null)
                return false;
        }
        else if (!this.bucket.equals(other.bucket))
            return false;
        if (this.prefix == null) {
            if (other.prefix != null)
                return false;
        }
        else if (!this.prefix.equals(other.prefix))
            return false;
        if (this.keyCount == null) {
            if (other.keyCount != null)
                return false;
        }
        else if (!this.keyCount.equals(other.keyCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.portalRunId == null) ? 0 : this.portalRunId.hashCode());
        result = prime * result + ((this.cohortId == null) ? 0 : this.cohortId.hashCode());
        result = prime * result + ((this.bucket == null) ? 0 : this.bucket.hashCode());
        result = prime * result + ((this.prefix == null) ? 0 : this.prefix.hashCode());
        result = prime * result + ((this.keyCount == null) ? 0 : this.keyCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WorkflowOutput (");

        sb.append(portalRunId);
        sb.append(", ").append(cohortId);
        sb.append(", ").append(bucket);
        sb.append(", ").append(prefix);
        sb.append(", ").append(keyCount);

        sb.append(")");
        return sb.toString();
    }
}
