/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowCostReport implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String portalRunId;
    private final String workflowName;
    private final String workflowVersion;
    private final String workflowStatus;
    private final BigDecimal totalCost;
    private final BigDecimal computeCost;
    private final BigDecimal licenseCost;
    private final String icaProject;
    private final String costUnit;

    public WorkflowCostReport(WorkflowCostReport value) {
        this.portalRunId = value.portalRunId;
        this.workflowName = value.workflowName;
        this.workflowVersion = value.workflowVersion;
        this.workflowStatus = value.workflowStatus;
        this.totalCost = value.totalCost;
        this.computeCost = value.computeCost;
        this.licenseCost = value.licenseCost;
        this.icaProject = value.icaProject;
        this.costUnit = value.costUnit;
    }

    public WorkflowCostReport(
        String portalRunId,
        String workflowName,
        String workflowVersion,
        String workflowStatus,
        BigDecimal totalCost,
        BigDecimal computeCost,
        BigDecimal licenseCost,
        String icaProject,
        String costUnit
    ) {
        this.portalRunId = portalRunId;
        this.workflowName = workflowName;
        this.workflowVersion = workflowVersion;
        this.workflowStatus = workflowStatus;
        this.totalCost = totalCost;
        this.computeCost = computeCost;
        this.licenseCost = licenseCost;
        this.icaProject = icaProject;
        this.costUnit = costUnit;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.portal_run_id</code>.
     */
    public String getPortalRunId() {
        return this.portalRunId;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.workflow_name</code>.
     */
    public String getWorkflowName() {
        return this.workflowName;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.workflow_version</code>.
     */
    public String getWorkflowVersion() {
        return this.workflowVersion;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.workflow_status</code>.
     */
    public String getWorkflowStatus() {
        return this.workflowStatus;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.total_cost</code>.
     */
    public BigDecimal getTotalCost() {
        return this.totalCost;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.compute_cost</code>.
     */
    public BigDecimal getComputeCost() {
        return this.computeCost;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.license_cost</code>.
     */
    public BigDecimal getLicenseCost() {
        return this.licenseCost;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.ica_project</code>.
     */
    public String getIcaProject() {
        return this.icaProject;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.cost_unit</code>.
     */
    public String getCostUnit() {
        return this.costUnit;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WorkflowCostReport other = (WorkflowCostReport) obj;
        if (this.portalRunId == null) {
            if (other.portalRunId != null)
                return false;
        }
        else if (!this.portalRunId.equals(other.portalRunId))
            return false;
        if (this.workflowName == null) {
            if (other.workflowName != null)
                return false;
        }
        else if (!this.workflowName.equals(other.workflowName))
            return false;
        if (this.workflowVersion == null) {
            if (other.workflowVersion != null)
                return false;
        }
        else if (!this.workflowVersion.equals(other.workflowVersion))
            return false;
        if (this.workflowStatus == null) {
            if (other.workflowStatus != null)
                return false;
        }
        else if (!this.workflowStatus.equals(other.workflowStatus))
            return false;
        if (this.totalCost == null) {
            if (other.totalCost != null)
                return false;
        }
        else if (!this.totalCost.equals(other.totalCost))
            return false;
        if (this.computeCost == null) {
            if (other.computeCost != null)
                return false;
        }
        else if (!this.computeCost.equals(other.computeCost))
            return false;
        if (this.licenseCost == null) {
            if (other.licenseCost != null)
                return false;
        }
        else if (!this.licenseCost.equals(other.licenseCost))
            return false;
        if (this.icaProject == null) {
            if (other.icaProject != null)
                return false;
        }
        else if (!this.icaProject.equals(other.icaProject))
            return false;
        if (this.costUnit == null) {
            if (other.costUnit != null)
                return false;
        }
        else if (!this.costUnit.equals(other.costUnit))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.portalRunId == null) ? 0 : this.portalRunId.hashCode());
        result = prime * result + ((this.workflowName == null) ? 0 : this.workflowName.hashCode());
        result = prime * result + ((this.workflowVersion == null) ? 0 : this.workflowVersion.hashCode());
        result = prime * result + ((this.workflowStatus == null) ? 0 : this.workflowStatus.hashCode());
        result = prime * result + ((this.totalCost == null) ? 0 : this.totalCost.hashCode());
        result = prime * result + ((this.computeCost == null) ? 0 : this.computeCost.hashCode());
        result = prime * result + ((this.licenseCost == null) ? 0 : this.licenseCost.hashCode());
        result = prime * result + ((this.icaProject == null) ? 0 : this.icaProject.hashCode());
        result = prime * result + ((this.costUnit == null) ? 0 : this.costUnit.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WorkflowCostReport (");

        sb.append(portalRunId);
        sb.append(", ").append(workflowName);
        sb.append(", ").append(workflowVersion);
        sb.append(", ").append(workflowStatus);
        sb.append(", ").append(totalCost);
        sb.append(", ").append(computeCost);
        sb.append(", ").append(licenseCost);
        sb.append(", ").append(icaProject);
        sb.append(", ").append(costUnit);

        sb.append(")");
        return sb.toString();
    }
}
