/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Workflow implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String portalRunId;
    private final String libraryId;
    private final String workflowName;
    private final String workflowVersion;
    private final String workflowStatus;
    private final LocalDateTime workflowStart;
    private final LocalDateTime workflowEnd;
    private final BigDecimal workflowDuration;
    private final String workflowComment;

    public Workflow(Workflow value) {
        this.portalRunId = value.portalRunId;
        this.libraryId = value.libraryId;
        this.workflowName = value.workflowName;
        this.workflowVersion = value.workflowVersion;
        this.workflowStatus = value.workflowStatus;
        this.workflowStart = value.workflowStart;
        this.workflowEnd = value.workflowEnd;
        this.workflowDuration = value.workflowDuration;
        this.workflowComment = value.workflowComment;
    }

    public Workflow(
        String portalRunId,
        String libraryId,
        String workflowName,
        String workflowVersion,
        String workflowStatus,
        LocalDateTime workflowStart,
        LocalDateTime workflowEnd,
        BigDecimal workflowDuration,
        String workflowComment
    ) {
        this.portalRunId = portalRunId;
        this.libraryId = libraryId;
        this.workflowName = workflowName;
        this.workflowVersion = workflowVersion;
        this.workflowStatus = workflowStatus;
        this.workflowStart = workflowStart;
        this.workflowEnd = workflowEnd;
        this.workflowDuration = workflowDuration;
        this.workflowComment = workflowComment;
    }

    /**
     * Getter for <code>mart.workflow.portal_run_id</code>.
     */
    public String getPortalRunId() {
        return this.portalRunId;
    }

    /**
     * Getter for <code>mart.workflow.library_id</code>.
     */
    public String getLibraryId() {
        return this.libraryId;
    }

    /**
     * Getter for <code>mart.workflow.workflow_name</code>.
     */
    public String getWorkflowName() {
        return this.workflowName;
    }

    /**
     * Getter for <code>mart.workflow.workflow_version</code>.
     */
    public String getWorkflowVersion() {
        return this.workflowVersion;
    }

    /**
     * Getter for <code>mart.workflow.workflow_status</code>.
     */
    public String getWorkflowStatus() {
        return this.workflowStatus;
    }

    /**
     * Getter for <code>mart.workflow.workflow_start</code>.
     */
    public LocalDateTime getWorkflowStart() {
        return this.workflowStart;
    }

    /**
     * Getter for <code>mart.workflow.workflow_end</code>.
     */
    public LocalDateTime getWorkflowEnd() {
        return this.workflowEnd;
    }

    /**
     * Getter for <code>mart.workflow.workflow_duration</code>.
     */
    public BigDecimal getWorkflowDuration() {
        return this.workflowDuration;
    }

    /**
     * Getter for <code>mart.workflow.workflow_comment</code>.
     */
    public String getWorkflowComment() {
        return this.workflowComment;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Workflow other = (Workflow) obj;
        if (this.portalRunId == null) {
            if (other.portalRunId != null)
                return false;
        }
        else if (!this.portalRunId.equals(other.portalRunId))
            return false;
        if (this.libraryId == null) {
            if (other.libraryId != null)
                return false;
        }
        else if (!this.libraryId.equals(other.libraryId))
            return false;
        if (this.workflowName == null) {
            if (other.workflowName != null)
                return false;
        }
        else if (!this.workflowName.equals(other.workflowName))
            return false;
        if (this.workflowVersion == null) {
            if (other.workflowVersion != null)
                return false;
        }
        else if (!this.workflowVersion.equals(other.workflowVersion))
            return false;
        if (this.workflowStatus == null) {
            if (other.workflowStatus != null)
                return false;
        }
        else if (!this.workflowStatus.equals(other.workflowStatus))
            return false;
        if (this.workflowStart == null) {
            if (other.workflowStart != null)
                return false;
        }
        else if (!this.workflowStart.equals(other.workflowStart))
            return false;
        if (this.workflowEnd == null) {
            if (other.workflowEnd != null)
                return false;
        }
        else if (!this.workflowEnd.equals(other.workflowEnd))
            return false;
        if (this.workflowDuration == null) {
            if (other.workflowDuration != null)
                return false;
        }
        else if (!this.workflowDuration.equals(other.workflowDuration))
            return false;
        if (this.workflowComment == null) {
            if (other.workflowComment != null)
                return false;
        }
        else if (!this.workflowComment.equals(other.workflowComment))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.portalRunId == null) ? 0 : this.portalRunId.hashCode());
        result = prime * result + ((this.libraryId == null) ? 0 : this.libraryId.hashCode());
        result = prime * result + ((this.workflowName == null) ? 0 : this.workflowName.hashCode());
        result = prime * result + ((this.workflowVersion == null) ? 0 : this.workflowVersion.hashCode());
        result = prime * result + ((this.workflowStatus == null) ? 0 : this.workflowStatus.hashCode());
        result = prime * result + ((this.workflowStart == null) ? 0 : this.workflowStart.hashCode());
        result = prime * result + ((this.workflowEnd == null) ? 0 : this.workflowEnd.hashCode());
        result = prime * result + ((this.workflowDuration == null) ? 0 : this.workflowDuration.hashCode());
        result = prime * result + ((this.workflowComment == null) ? 0 : this.workflowComment.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Workflow (");

        sb.append(portalRunId);
        sb.append(", ").append(libraryId);
        sb.append(", ").append(workflowName);
        sb.append(", ").append(workflowVersion);
        sb.append(", ").append(workflowStatus);
        sb.append(", ").append(workflowStart);
        sb.append(", ").append(workflowEnd);
        sb.append(", ").append(workflowDuration);
        sb.append(", ").append(workflowComment);

        sb.append(")");
        return sb.toString();
    }
}
