/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq;


import dev.ccgcm.platform.orcanexus.jooq.tables.Bam;
import dev.ccgcm.platform.orcanexus.jooq.tables.Fastq;
import dev.ccgcm.platform.orcanexus.jooq.tables.Lims;
import dev.ccgcm.platform.orcanexus.jooq.tables.Vcf;
import dev.ccgcm.platform.orcanexus.jooq.tables.Workflow;
import dev.ccgcm.platform.orcanexus.jooq.tables.WorkflowCostReport;
import dev.ccgcm.platform.orcanexus.jooq.tables.WorkflowOutput;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Mart extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mart</code>
     */
    public static final Mart MART = new Mart();

    /**
     * The table <code>mart.bam</code>.
     */
    public final Bam BAM = Bam.BAM;

    /**
     * The table <code>mart.fastq</code>.
     */
    public final Fastq FASTQ = Fastq.FASTQ;

    /**
     * The table <code>mart.lims</code>.
     */
    public final Lims LIMS = Lims.LIMS;

    /**
     * The table <code>mart.vcf</code>.
     */
    public final Vcf VCF = Vcf.VCF;

    /**
     * The table <code>mart.workflow</code>.
     */
    public final Workflow WORKFLOW = Workflow.WORKFLOW;

    /**
     * The table <code>mart.workflow_cost_report</code>.
     */
    public final WorkflowCostReport WORKFLOW_COST_REPORT = WorkflowCostReport.WORKFLOW_COST_REPORT;

    /**
     * The table <code>mart.workflow_output</code>.
     */
    public final WorkflowOutput WORKFLOW_OUTPUT = WorkflowOutput.WORKFLOW_OUTPUT;

    /**
     * No further instances allowed
     */
    private Mart() {
        super(DSL.name("mart"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Bam.BAM,
            Fastq.FASTQ,
            Lims.LIMS,
            Vcf.VCF,
            Workflow.WORKFLOW,
            WorkflowCostReport.WORKFLOW_COST_REPORT,
            WorkflowOutput.WORKFLOW_OUTPUT
        );
    }
}
