/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq;


import dev.ccgcm.platform.orcanexus.jooq.tables.Bam;
import dev.ccgcm.platform.orcanexus.jooq.tables.Fastq;
import dev.ccgcm.platform.orcanexus.jooq.tables.Lims;
import dev.ccgcm.platform.orcanexus.jooq.tables.Vcf;
import dev.ccgcm.platform.orcanexus.jooq.tables.Workflow;
import dev.ccgcm.platform.orcanexus.jooq.tables.WorkflowCostReport;
import dev.ccgcm.platform.orcanexus.jooq.tables.WorkflowOutput;


/**
 * Convenience access to all tables in mart.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>mart.bam</code>.
     */
    public static final Bam BAM = Bam.BAM;

    /**
     * The table <code>mart.fastq</code>.
     */
    public static final Fastq FASTQ = Fastq.FASTQ;

    /**
     * The table <code>mart.lims</code>.
     */
    public static final Lims LIMS = Lims.LIMS;

    /**
     * The table <code>mart.vcf</code>.
     */
    public static final Vcf VCF = Vcf.VCF;

    /**
     * The table <code>mart.workflow</code>.
     */
    public static final Workflow WORKFLOW = Workflow.WORKFLOW;

    /**
     * The table <code>mart.workflow_cost_report</code>.
     */
    public static final WorkflowCostReport WORKFLOW_COST_REPORT = WorkflowCostReport.WORKFLOW_COST_REPORT;

    /**
     * The table <code>mart.workflow_output</code>.
     */
    public static final WorkflowOutput WORKFLOW_OUTPUT = WorkflowOutput.WORKFLOW_OUTPUT;
}
