/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables;


import dev.ccgcm.platform.orcanexus.jooq.Mart;
import dev.ccgcm.platform.orcanexus.jooq.tables.records.BamRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Bam extends TableImpl<BamRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mart.bam</code>
     */
    public static final Bam BAM = new Bam();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BamRecord> getRecordType() {
        return BamRecord.class;
    }

    /**
     * The column <code>mart.bam.portal_run_id</code>.
     */
    public final TableField<BamRecord, String> PORTAL_RUN_ID = createField(DSL.name("portal_run_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.bam.cohort_id</code>.
     */
    public final TableField<BamRecord, String> COHORT_ID = createField(DSL.name("cohort_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.bam.bucket</code>.
     */
    public final TableField<BamRecord, String> BUCKET = createField(DSL.name("bucket"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.bam.key</code>.
     */
    public final TableField<BamRecord, String> KEY = createField(DSL.name("key"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.bam.library_id</code>.
     */
    public final TableField<BamRecord, String> LIBRARY_ID = createField(DSL.name("library_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.bam.filename</code>.
     */
    public final TableField<BamRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.bam.format</code>.
     */
    public final TableField<BamRecord, String> FORMAT = createField(DSL.name("format"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.bam.size</code>.
     */
    public final TableField<BamRecord, Long> SIZE = createField(DSL.name("size"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>mart.bam.storage_class</code>.
     */
    public final TableField<BamRecord, String> STORAGE_CLASS = createField(DSL.name("storage_class"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.bam.e_tag</code>.
     */
    public final TableField<BamRecord, String> E_TAG = createField(DSL.name("e_tag"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.bam.last_modified_date</code>.
     */
    public final TableField<BamRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    private Bam(Name alias, Table<BamRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Bam(Name alias, Table<BamRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>mart.bam</code> table reference
     */
    public Bam(String alias) {
        this(DSL.name(alias), BAM);
    }

    /**
     * Create an aliased <code>mart.bam</code> table reference
     */
    public Bam(Name alias) {
        this(alias, BAM);
    }

    /**
     * Create a <code>mart.bam</code> table reference
     */
    public Bam() {
        this(DSL.name("bam"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Mart.MART;
    }

    @Override
    public Bam as(String alias) {
        return new Bam(DSL.name(alias), this);
    }

    @Override
    public Bam as(Name alias) {
        return new Bam(alias, this);
    }

    @Override
    public Bam as(Table<?> alias) {
        return new Bam(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bam rename(String name) {
        return new Bam(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bam rename(Name name) {
        return new Bam(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bam rename(Table<?> name) {
        return new Bam(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bam where(Condition condition) {
        return new Bam(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bam where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bam where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bam where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bam where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bam where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bam where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bam where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bam whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bam whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
