/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables;


import dev.ccgcm.platform.orcanexus.jooq.Mart;
import dev.ccgcm.platform.orcanexus.jooq.tables.records.FastqRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Fastq extends TableImpl<FastqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mart.fastq</code>
     */
    public static final Fastq FASTQ = new Fastq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FastqRecord> getRecordType() {
        return FastqRecord.class;
    }

    /**
     * The column <code>mart.fastq.sequencing_run_id</code>.
     */
    public final TableField<FastqRecord, String> SEQUENCING_RUN_ID = createField(DSL.name("sequencing_run_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.fastq.sequencing_run_date</code>.
     */
    public final TableField<FastqRecord, LocalDate> SEQUENCING_RUN_DATE = createField(DSL.name("sequencing_run_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>mart.fastq.portal_run_id</code>.
     */
    public final TableField<FastqRecord, String> PORTAL_RUN_ID = createField(DSL.name("portal_run_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.fastq.cohort_id</code>.
     */
    public final TableField<FastqRecord, String> COHORT_ID = createField(DSL.name("cohort_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.fastq.bucket</code>.
     */
    public final TableField<FastqRecord, String> BUCKET = createField(DSL.name("bucket"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.fastq.key</code>.
     */
    public final TableField<FastqRecord, String> KEY = createField(DSL.name("key"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.fastq.library_id</code>.
     */
    public final TableField<FastqRecord, String> LIBRARY_ID = createField(DSL.name("library_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.fastq.filename</code>.
     */
    public final TableField<FastqRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.fastq.format</code>.
     */
    public final TableField<FastqRecord, String> FORMAT = createField(DSL.name("format"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.fastq.size</code>.
     */
    public final TableField<FastqRecord, Long> SIZE = createField(DSL.name("size"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>mart.fastq.storage_class</code>.
     */
    public final TableField<FastqRecord, String> STORAGE_CLASS = createField(DSL.name("storage_class"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.fastq.e_tag</code>.
     */
    public final TableField<FastqRecord, String> E_TAG = createField(DSL.name("e_tag"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.fastq.last_modified_date</code>.
     */
    public final TableField<FastqRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    private Fastq(Name alias, Table<FastqRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Fastq(Name alias, Table<FastqRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>mart.fastq</code> table reference
     */
    public Fastq(String alias) {
        this(DSL.name(alias), FASTQ);
    }

    /**
     * Create an aliased <code>mart.fastq</code> table reference
     */
    public Fastq(Name alias) {
        this(alias, FASTQ);
    }

    /**
     * Create a <code>mart.fastq</code> table reference
     */
    public Fastq() {
        this(DSL.name("fastq"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Mart.MART;
    }

    @Override
    public Fastq as(String alias) {
        return new Fastq(DSL.name(alias), this);
    }

    @Override
    public Fastq as(Name alias) {
        return new Fastq(alias, this);
    }

    @Override
    public Fastq as(Table<?> alias) {
        return new Fastq(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Fastq rename(String name) {
        return new Fastq(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Fastq rename(Name name) {
        return new Fastq(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Fastq rename(Table<?> name) {
        return new Fastq(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fastq where(Condition condition) {
        return new Fastq(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fastq where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fastq where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fastq where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fastq where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fastq where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fastq where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fastq where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fastq whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fastq whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
