/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables;


import dev.ccgcm.platform.orcanexus.jooq.Mart;
import dev.ccgcm.platform.orcanexus.jooq.tables.records.LimsRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lims extends TableImpl<LimsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mart.lims</code>
     */
    public static final Lims LIMS = new Lims();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LimsRecord> getRecordType() {
        return LimsRecord.class;
    }

    /**
     * The column <code>mart.lims.sequencing_run_id</code>.
     */
    public final TableField<LimsRecord, String> SEQUENCING_RUN_ID = createField(DSL.name("sequencing_run_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.sequencing_run_date</code>.
     */
    public final TableField<LimsRecord, LocalDate> SEQUENCING_RUN_DATE = createField(DSL.name("sequencing_run_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>mart.lims.library_id</code>.
     */
    public final TableField<LimsRecord, String> LIBRARY_ID = createField(DSL.name("library_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.alias_library_id</code>.
     */
    public final TableField<LimsRecord, String> ALIAS_LIBRARY_ID = createField(DSL.name("alias_library_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.internal_subject_id</code>.
     */
    public final TableField<LimsRecord, String> INTERNAL_SUBJECT_ID = createField(DSL.name("internal_subject_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.external_subject_id</code>.
     */
    public final TableField<LimsRecord, String> EXTERNAL_SUBJECT_ID = createField(DSL.name("external_subject_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.sample_id</code>.
     */
    public final TableField<LimsRecord, String> SAMPLE_ID = createField(DSL.name("sample_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.external_sample_id</code>.
     */
    public final TableField<LimsRecord, String> EXTERNAL_SAMPLE_ID = createField(DSL.name("external_sample_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.experiment_id</code>.
     */
    public final TableField<LimsRecord, String> EXPERIMENT_ID = createField(DSL.name("experiment_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.project_id</code>.
     */
    public final TableField<LimsRecord, String> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.owner_id</code>.
     */
    public final TableField<LimsRecord, String> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.workflow</code>.
     */
    public final TableField<LimsRecord, String> WORKFLOW = createField(DSL.name("workflow"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.phenotype</code>.
     */
    public final TableField<LimsRecord, String> PHENOTYPE = createField(DSL.name("phenotype"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.type</code>.
     */
    public final TableField<LimsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.assay</code>.
     */
    public final TableField<LimsRecord, String> ASSAY = createField(DSL.name("assay"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.quality</code>.
     */
    public final TableField<LimsRecord, String> QUALITY = createField(DSL.name("quality"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.source</code>.
     */
    public final TableField<LimsRecord, String> SOURCE = createField(DSL.name("source"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.truseq_index</code>.
     */
    public final TableField<LimsRecord, String> TRUSEQ_INDEX = createField(DSL.name("truseq_index"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.lims.load_datetime</code>.
     */
    public final TableField<LimsRecord, LocalDateTime> LOAD_DATETIME = createField(DSL.name("load_datetime"), SQLDataType.LOCALDATETIME(6), this, "");

    private Lims(Name alias, Table<LimsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lims(Name alias, Table<LimsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>mart.lims</code> table reference
     */
    public Lims(String alias) {
        this(DSL.name(alias), LIMS);
    }

    /**
     * Create an aliased <code>mart.lims</code> table reference
     */
    public Lims(Name alias) {
        this(alias, LIMS);
    }

    /**
     * Create a <code>mart.lims</code> table reference
     */
    public Lims() {
        this(DSL.name("lims"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Mart.MART;
    }

    @Override
    public Lims as(String alias) {
        return new Lims(DSL.name(alias), this);
    }

    @Override
    public Lims as(Name alias) {
        return new Lims(alias, this);
    }

    @Override
    public Lims as(Table<?> alias) {
        return new Lims(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lims rename(String name) {
        return new Lims(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lims rename(Name name) {
        return new Lims(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lims rename(Table<?> name) {
        return new Lims(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lims where(Condition condition) {
        return new Lims(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lims where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lims where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lims where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lims where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lims where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lims where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lims where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lims whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lims whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
