/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables;


import dev.ccgcm.platform.orcanexus.jooq.Mart;
import dev.ccgcm.platform.orcanexus.jooq.tables.records.VcfRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Vcf extends TableImpl<VcfRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mart.vcf</code>
     */
    public static final Vcf VCF = new Vcf();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VcfRecord> getRecordType() {
        return VcfRecord.class;
    }

    /**
     * The column <code>mart.vcf.portal_run_id</code>.
     */
    public final TableField<VcfRecord, String> PORTAL_RUN_ID = createField(DSL.name("portal_run_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.vcf.cohort_id</code>.
     */
    public final TableField<VcfRecord, String> COHORT_ID = createField(DSL.name("cohort_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.vcf.bucket</code>.
     */
    public final TableField<VcfRecord, String> BUCKET = createField(DSL.name("bucket"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.vcf.key</code>.
     */
    public final TableField<VcfRecord, String> KEY = createField(DSL.name("key"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.vcf.library_id</code>.
     */
    public final TableField<VcfRecord, String> LIBRARY_ID = createField(DSL.name("library_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.vcf.filename</code>.
     */
    public final TableField<VcfRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.vcf.format</code>.
     */
    public final TableField<VcfRecord, String> FORMAT = createField(DSL.name("format"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.vcf.size</code>.
     */
    public final TableField<VcfRecord, Long> SIZE = createField(DSL.name("size"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>mart.vcf.storage_class</code>.
     */
    public final TableField<VcfRecord, String> STORAGE_CLASS = createField(DSL.name("storage_class"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.vcf.e_tag</code>.
     */
    public final TableField<VcfRecord, String> E_TAG = createField(DSL.name("e_tag"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.vcf.last_modified_date</code>.
     */
    public final TableField<VcfRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    private Vcf(Name alias, Table<VcfRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Vcf(Name alias, Table<VcfRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>mart.vcf</code> table reference
     */
    public Vcf(String alias) {
        this(DSL.name(alias), VCF);
    }

    /**
     * Create an aliased <code>mart.vcf</code> table reference
     */
    public Vcf(Name alias) {
        this(alias, VCF);
    }

    /**
     * Create a <code>mart.vcf</code> table reference
     */
    public Vcf() {
        this(DSL.name("vcf"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Mart.MART;
    }

    @Override
    public Vcf as(String alias) {
        return new Vcf(DSL.name(alias), this);
    }

    @Override
    public Vcf as(Name alias) {
        return new Vcf(alias, this);
    }

    @Override
    public Vcf as(Table<?> alias) {
        return new Vcf(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Vcf rename(String name) {
        return new Vcf(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vcf rename(Name name) {
        return new Vcf(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vcf rename(Table<?> name) {
        return new Vcf(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vcf where(Condition condition) {
        return new Vcf(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vcf where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vcf where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vcf where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vcf where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vcf where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vcf where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vcf where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vcf whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vcf whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
