/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables;


import dev.ccgcm.platform.orcanexus.jooq.Mart;
import dev.ccgcm.platform.orcanexus.jooq.tables.records.WorkflowRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Workflow extends TableImpl<WorkflowRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mart.workflow</code>
     */
    public static final Workflow WORKFLOW = new Workflow();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkflowRecord> getRecordType() {
        return WorkflowRecord.class;
    }

    /**
     * The column <code>mart.workflow.portal_run_id</code>.
     */
    public final TableField<WorkflowRecord, String> PORTAL_RUN_ID = createField(DSL.name("portal_run_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow.library_id</code>.
     */
    public final TableField<WorkflowRecord, String> LIBRARY_ID = createField(DSL.name("library_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow.workflow_name</code>.
     */
    public final TableField<WorkflowRecord, String> WORKFLOW_NAME = createField(DSL.name("workflow_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow.workflow_version</code>.
     */
    public final TableField<WorkflowRecord, String> WORKFLOW_VERSION = createField(DSL.name("workflow_version"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow.workflow_status</code>.
     */
    public final TableField<WorkflowRecord, String> WORKFLOW_STATUS = createField(DSL.name("workflow_status"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow.workflow_start</code>.
     */
    public final TableField<WorkflowRecord, LocalDateTime> WORKFLOW_START = createField(DSL.name("workflow_start"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>mart.workflow.workflow_end</code>.
     */
    public final TableField<WorkflowRecord, LocalDateTime> WORKFLOW_END = createField(DSL.name("workflow_end"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>mart.workflow.workflow_duration</code>.
     */
    public final TableField<WorkflowRecord, BigDecimal> WORKFLOW_DURATION = createField(DSL.name("workflow_duration"), SQLDataType.NUMERIC(12, 4), this, "");

    /**
     * The column <code>mart.workflow.workflow_comment</code>.
     */
    public final TableField<WorkflowRecord, String> WORKFLOW_COMMENT = createField(DSL.name("workflow_comment"), SQLDataType.CLOB, this, "");

    private Workflow(Name alias, Table<WorkflowRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Workflow(Name alias, Table<WorkflowRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>mart.workflow</code> table reference
     */
    public Workflow(String alias) {
        this(DSL.name(alias), WORKFLOW);
    }

    /**
     * Create an aliased <code>mart.workflow</code> table reference
     */
    public Workflow(Name alias) {
        this(alias, WORKFLOW);
    }

    /**
     * Create a <code>mart.workflow</code> table reference
     */
    public Workflow() {
        this(DSL.name("workflow"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Mart.MART;
    }

    @Override
    public Workflow as(String alias) {
        return new Workflow(DSL.name(alias), this);
    }

    @Override
    public Workflow as(Name alias) {
        return new Workflow(alias, this);
    }

    @Override
    public Workflow as(Table<?> alias) {
        return new Workflow(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Workflow rename(String name) {
        return new Workflow(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Workflow rename(Name name) {
        return new Workflow(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Workflow rename(Table<?> name) {
        return new Workflow(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workflow where(Condition condition) {
        return new Workflow(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workflow where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workflow where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workflow where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Workflow where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Workflow where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Workflow where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Workflow where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workflow whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workflow whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
