/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables;


import dev.ccgcm.platform.orcanexus.jooq.Mart;
import dev.ccgcm.platform.orcanexus.jooq.tables.records.WorkflowOutputRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowOutput extends TableImpl<WorkflowOutputRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mart.workflow_output</code>
     */
    public static final WorkflowOutput WORKFLOW_OUTPUT = new WorkflowOutput();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkflowOutputRecord> getRecordType() {
        return WorkflowOutputRecord.class;
    }

    /**
     * The column <code>mart.workflow_output.portal_run_id</code>.
     */
    public final TableField<WorkflowOutputRecord, String> PORTAL_RUN_ID = createField(DSL.name("portal_run_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow_output.cohort_id</code>.
     */
    public final TableField<WorkflowOutputRecord, String> COHORT_ID = createField(DSL.name("cohort_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow_output.bucket</code>.
     */
    public final TableField<WorkflowOutputRecord, String> BUCKET = createField(DSL.name("bucket"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow_output.prefix</code>.
     */
    public final TableField<WorkflowOutputRecord, String> PREFIX = createField(DSL.name("prefix"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow_output.key_count</code>.
     */
    public final TableField<WorkflowOutputRecord, Long> KEY_COUNT = createField(DSL.name("key_count"), SQLDataType.BIGINT, this, "");

    private WorkflowOutput(Name alias, Table<WorkflowOutputRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WorkflowOutput(Name alias, Table<WorkflowOutputRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>mart.workflow_output</code> table reference
     */
    public WorkflowOutput(String alias) {
        this(DSL.name(alias), WORKFLOW_OUTPUT);
    }

    /**
     * Create an aliased <code>mart.workflow_output</code> table reference
     */
    public WorkflowOutput(Name alias) {
        this(alias, WORKFLOW_OUTPUT);
    }

    /**
     * Create a <code>mart.workflow_output</code> table reference
     */
    public WorkflowOutput() {
        this(DSL.name("workflow_output"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Mart.MART;
    }

    @Override
    public WorkflowOutput as(String alias) {
        return new WorkflowOutput(DSL.name(alias), this);
    }

    @Override
    public WorkflowOutput as(Name alias) {
        return new WorkflowOutput(alias, this);
    }

    @Override
    public WorkflowOutput as(Table<?> alias) {
        return new WorkflowOutput(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkflowOutput rename(String name) {
        return new WorkflowOutput(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkflowOutput rename(Name name) {
        return new WorkflowOutput(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkflowOutput rename(Table<?> name) {
        return new WorkflowOutput(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowOutput where(Condition condition) {
        return new WorkflowOutput(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowOutput where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowOutput where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowOutput where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorkflowOutput where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorkflowOutput where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorkflowOutput where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorkflowOutput where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowOutput whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowOutput whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
