/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables;


import dev.ccgcm.platform.orcanexus.jooq.Mart;
import dev.ccgcm.platform.orcanexus.jooq.tables.records.WorkflowCostReportRecord;

import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowCostReport extends TableImpl<WorkflowCostReportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mart.workflow_cost_report</code>
     */
    public static final WorkflowCostReport WORKFLOW_COST_REPORT = new WorkflowCostReport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkflowCostReportRecord> getRecordType() {
        return WorkflowCostReportRecord.class;
    }

    /**
     * The column <code>mart.workflow_cost_report.portal_run_id</code>.
     */
    public final TableField<WorkflowCostReportRecord, String> PORTAL_RUN_ID = createField(DSL.name("portal_run_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow_cost_report.workflow_name</code>.
     */
    public final TableField<WorkflowCostReportRecord, String> WORKFLOW_NAME = createField(DSL.name("workflow_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow_cost_report.workflow_version</code>.
     */
    public final TableField<WorkflowCostReportRecord, String> WORKFLOW_VERSION = createField(DSL.name("workflow_version"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow_cost_report.workflow_status</code>.
     */
    public final TableField<WorkflowCostReportRecord, String> WORKFLOW_STATUS = createField(DSL.name("workflow_status"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow_cost_report.total_cost</code>.
     */
    public final TableField<WorkflowCostReportRecord, BigDecimal> TOTAL_COST = createField(DSL.name("total_cost"), SQLDataType.NUMERIC(18, 2), this, "");

    /**
     * The column <code>mart.workflow_cost_report.compute_cost</code>.
     */
    public final TableField<WorkflowCostReportRecord, BigDecimal> COMPUTE_COST = createField(DSL.name("compute_cost"), SQLDataType.NUMERIC(18, 2), this, "");

    /**
     * The column <code>mart.workflow_cost_report.license_cost</code>.
     */
    public final TableField<WorkflowCostReportRecord, BigDecimal> LICENSE_COST = createField(DSL.name("license_cost"), SQLDataType.NUMERIC(18, 2), this, "");

    /**
     * The column <code>mart.workflow_cost_report.ica_project</code>.
     */
    public final TableField<WorkflowCostReportRecord, String> ICA_PROJECT = createField(DSL.name("ica_project"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>mart.workflow_cost_report.cost_unit</code>.
     */
    public final TableField<WorkflowCostReportRecord, String> COST_UNIT = createField(DSL.name("cost_unit"), SQLDataType.CLOB, this, "");

    private WorkflowCostReport(Name alias, Table<WorkflowCostReportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WorkflowCostReport(Name alias, Table<WorkflowCostReportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>mart.workflow_cost_report</code> table reference
     */
    public WorkflowCostReport(String alias) {
        this(DSL.name(alias), WORKFLOW_COST_REPORT);
    }

    /**
     * Create an aliased <code>mart.workflow_cost_report</code> table reference
     */
    public WorkflowCostReport(Name alias) {
        this(alias, WORKFLOW_COST_REPORT);
    }

    /**
     * Create a <code>mart.workflow_cost_report</code> table reference
     */
    public WorkflowCostReport() {
        this(DSL.name("workflow_cost_report"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Mart.MART;
    }

    @Override
    public WorkflowCostReport as(String alias) {
        return new WorkflowCostReport(DSL.name(alias), this);
    }

    @Override
    public WorkflowCostReport as(Name alias) {
        return new WorkflowCostReport(alias, this);
    }

    @Override
    public WorkflowCostReport as(Table<?> alias) {
        return new WorkflowCostReport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkflowCostReport rename(String name) {
        return new WorkflowCostReport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkflowCostReport rename(Name name) {
        return new WorkflowCostReport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkflowCostReport rename(Table<?> name) {
        return new WorkflowCostReport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowCostReport where(Condition condition) {
        return new WorkflowCostReport(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowCostReport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowCostReport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowCostReport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorkflowCostReport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorkflowCostReport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorkflowCostReport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorkflowCostReport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowCostReport whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorkflowCostReport whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
