/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.records;


import dev.ccgcm.platform.orcanexus.jooq.tables.Bam;

import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BamRecord extends TableRecordImpl<BamRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mart.bam.portal_run_id</code>.
     */
    public BamRecord setPortalRunId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.portal_run_id</code>.
     */
    public String getPortalRunId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mart.bam.cohort_id</code>.
     */
    public BamRecord setCohortId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.cohort_id</code>.
     */
    public String getCohortId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mart.bam.bucket</code>.
     */
    public BamRecord setBucket(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.bucket</code>.
     */
    public String getBucket() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mart.bam.key</code>.
     */
    public BamRecord setKey(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.key</code>.
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mart.bam.library_id</code>.
     */
    public BamRecord setLibraryId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.library_id</code>.
     */
    public String getLibraryId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mart.bam.filename</code>.
     */
    public BamRecord setFilename(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.filename</code>.
     */
    public String getFilename() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mart.bam.format</code>.
     */
    public BamRecord setFormat(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.format</code>.
     */
    public String getFormat() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mart.bam.size</code>.
     */
    public BamRecord setSize(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.size</code>.
     */
    public Long getSize() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>mart.bam.storage_class</code>.
     */
    public BamRecord setStorageClass(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.storage_class</code>.
     */
    public String getStorageClass() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mart.bam.e_tag</code>.
     */
    public BamRecord setETag(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.e_tag</code>.
     */
    public String getETag() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mart.bam.last_modified_date</code>.
     */
    public BamRecord setLastModifiedDate(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>mart.bam.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BamRecord
     */
    public BamRecord() {
        super(Bam.BAM);
    }

    /**
     * Create a detached, initialised BamRecord
     */
    public BamRecord(String portalRunId, String cohortId, String bucket, String key, String libraryId, String filename, String format, Long size, String storageClass, String eTag, LocalDateTime lastModifiedDate) {
        super(Bam.BAM);

        setPortalRunId(portalRunId);
        setCohortId(cohortId);
        setBucket(bucket);
        setKey(key);
        setLibraryId(libraryId);
        setFilename(filename);
        setFormat(format);
        setSize(size);
        setStorageClass(storageClass);
        setETag(eTag);
        setLastModifiedDate(lastModifiedDate);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised BamRecord
     */
    public BamRecord(dev.ccgcm.platform.orcanexus.jooq.tables.pojos.Bam value) {
        super(Bam.BAM);

        if (value != null) {
            setPortalRunId(value.getPortalRunId());
            setCohortId(value.getCohortId());
            setBucket(value.getBucket());
            setKey(value.getKey());
            setLibraryId(value.getLibraryId());
            setFilename(value.getFilename());
            setFormat(value.getFormat());
            setSize(value.getSize());
            setStorageClass(value.getStorageClass());
            setETag(value.getETag());
            setLastModifiedDate(value.getLastModifiedDate());
            resetTouchedOnNotNull();
        }
    }
}
