/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.records;


import dev.ccgcm.platform.orcanexus.jooq.tables.Fastq;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FastqRecord extends TableRecordImpl<FastqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mart.fastq.sequencing_run_id</code>.
     */
    public FastqRecord setSequencingRunId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.sequencing_run_id</code>.
     */
    public String getSequencingRunId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mart.fastq.sequencing_run_date</code>.
     */
    public FastqRecord setSequencingRunDate(LocalDate value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.sequencing_run_date</code>.
     */
    public LocalDate getSequencingRunDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>mart.fastq.portal_run_id</code>.
     */
    public FastqRecord setPortalRunId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.portal_run_id</code>.
     */
    public String getPortalRunId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mart.fastq.cohort_id</code>.
     */
    public FastqRecord setCohortId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.cohort_id</code>.
     */
    public String getCohortId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mart.fastq.bucket</code>.
     */
    public FastqRecord setBucket(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.bucket</code>.
     */
    public String getBucket() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mart.fastq.key</code>.
     */
    public FastqRecord setKey(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.key</code>.
     */
    public String getKey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mart.fastq.library_id</code>.
     */
    public FastqRecord setLibraryId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.library_id</code>.
     */
    public String getLibraryId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mart.fastq.filename</code>.
     */
    public FastqRecord setFilename(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.filename</code>.
     */
    public String getFilename() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mart.fastq.format</code>.
     */
    public FastqRecord setFormat(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.format</code>.
     */
    public String getFormat() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mart.fastq.size</code>.
     */
    public FastqRecord setSize(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.size</code>.
     */
    public Long getSize() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>mart.fastq.storage_class</code>.
     */
    public FastqRecord setStorageClass(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.storage_class</code>.
     */
    public String getStorageClass() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mart.fastq.e_tag</code>.
     */
    public FastqRecord setETag(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.e_tag</code>.
     */
    public String getETag() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mart.fastq.last_modified_date</code>.
     */
    public FastqRecord setLastModifiedDate(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>mart.fastq.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FastqRecord
     */
    public FastqRecord() {
        super(Fastq.FASTQ);
    }

    /**
     * Create a detached, initialised FastqRecord
     */
    public FastqRecord(String sequencingRunId, LocalDate sequencingRunDate, String portalRunId, String cohortId, String bucket, String key, String libraryId, String filename, String format, Long size, String storageClass, String eTag, LocalDateTime lastModifiedDate) {
        super(Fastq.FASTQ);

        setSequencingRunId(sequencingRunId);
        setSequencingRunDate(sequencingRunDate);
        setPortalRunId(portalRunId);
        setCohortId(cohortId);
        setBucket(bucket);
        setKey(key);
        setLibraryId(libraryId);
        setFilename(filename);
        setFormat(format);
        setSize(size);
        setStorageClass(storageClass);
        setETag(eTag);
        setLastModifiedDate(lastModifiedDate);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised FastqRecord
     */
    public FastqRecord(dev.ccgcm.platform.orcanexus.jooq.tables.pojos.Fastq value) {
        super(Fastq.FASTQ);

        if (value != null) {
            setSequencingRunId(value.getSequencingRunId());
            setSequencingRunDate(value.getSequencingRunDate());
            setPortalRunId(value.getPortalRunId());
            setCohortId(value.getCohortId());
            setBucket(value.getBucket());
            setKey(value.getKey());
            setLibraryId(value.getLibraryId());
            setFilename(value.getFilename());
            setFormat(value.getFormat());
            setSize(value.getSize());
            setStorageClass(value.getStorageClass());
            setETag(value.getETag());
            setLastModifiedDate(value.getLastModifiedDate());
            resetTouchedOnNotNull();
        }
    }
}
