/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.records;


import dev.ccgcm.platform.orcanexus.jooq.tables.Lims;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LimsRecord extends TableRecordImpl<LimsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mart.lims.sequencing_run_id</code>.
     */
    public LimsRecord setSequencingRunId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.sequencing_run_id</code>.
     */
    public String getSequencingRunId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mart.lims.sequencing_run_date</code>.
     */
    public LimsRecord setSequencingRunDate(LocalDate value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.sequencing_run_date</code>.
     */
    public LocalDate getSequencingRunDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>mart.lims.library_id</code>.
     */
    public LimsRecord setLibraryId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.library_id</code>.
     */
    public String getLibraryId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mart.lims.alias_library_id</code>.
     */
    public LimsRecord setAliasLibraryId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.alias_library_id</code>.
     */
    public String getAliasLibraryId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mart.lims.internal_subject_id</code>.
     */
    public LimsRecord setInternalSubjectId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.internal_subject_id</code>.
     */
    public String getInternalSubjectId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mart.lims.external_subject_id</code>.
     */
    public LimsRecord setExternalSubjectId(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.external_subject_id</code>.
     */
    public String getExternalSubjectId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mart.lims.sample_id</code>.
     */
    public LimsRecord setSampleId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.sample_id</code>.
     */
    public String getSampleId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mart.lims.external_sample_id</code>.
     */
    public LimsRecord setExternalSampleId(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.external_sample_id</code>.
     */
    public String getExternalSampleId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mart.lims.experiment_id</code>.
     */
    public LimsRecord setExperimentId(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.experiment_id</code>.
     */
    public String getExperimentId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mart.lims.project_id</code>.
     */
    public LimsRecord setProjectId(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.project_id</code>.
     */
    public String getProjectId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mart.lims.owner_id</code>.
     */
    public LimsRecord setOwnerId(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.owner_id</code>.
     */
    public String getOwnerId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mart.lims.workflow</code>.
     */
    public LimsRecord setWorkflow(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.workflow</code>.
     */
    public String getWorkflow() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mart.lims.phenotype</code>.
     */
    public LimsRecord setPhenotype(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.phenotype</code>.
     */
    public String getPhenotype() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mart.lims.type</code>.
     */
    public LimsRecord setType(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.type</code>.
     */
    public String getType() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mart.lims.assay</code>.
     */
    public LimsRecord setAssay(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.assay</code>.
     */
    public String getAssay() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mart.lims.quality</code>.
     */
    public LimsRecord setQuality(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.quality</code>.
     */
    public String getQuality() {
        return (String) get(15);
    }

    /**
     * Setter for <code>mart.lims.source</code>.
     */
    public LimsRecord setSource(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.source</code>.
     */
    public String getSource() {
        return (String) get(16);
    }

    /**
     * Setter for <code>mart.lims.truseq_index</code>.
     */
    public LimsRecord setTruseqIndex(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.truseq_index</code>.
     */
    public String getTruseqIndex() {
        return (String) get(17);
    }

    /**
     * Setter for <code>mart.lims.load_datetime</code>.
     */
    public LimsRecord setLoadDatetime(LocalDateTime value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>mart.lims.load_datetime</code>.
     */
    public LocalDateTime getLoadDatetime() {
        return (LocalDateTime) get(18);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LimsRecord
     */
    public LimsRecord() {
        super(Lims.LIMS);
    }

    /**
     * Create a detached, initialised LimsRecord
     */
    public LimsRecord(String sequencingRunId, LocalDate sequencingRunDate, String libraryId, String aliasLibraryId, String internalSubjectId, String externalSubjectId, String sampleId, String externalSampleId, String experimentId, String projectId, String ownerId, String workflow, String phenotype, String type, String assay, String quality, String source, String truseqIndex, LocalDateTime loadDatetime) {
        super(Lims.LIMS);

        setSequencingRunId(sequencingRunId);
        setSequencingRunDate(sequencingRunDate);
        setLibraryId(libraryId);
        setAliasLibraryId(aliasLibraryId);
        setInternalSubjectId(internalSubjectId);
        setExternalSubjectId(externalSubjectId);
        setSampleId(sampleId);
        setExternalSampleId(externalSampleId);
        setExperimentId(experimentId);
        setProjectId(projectId);
        setOwnerId(ownerId);
        setWorkflow(workflow);
        setPhenotype(phenotype);
        setType(type);
        setAssay(assay);
        setQuality(quality);
        setSource(source);
        setTruseqIndex(truseqIndex);
        setLoadDatetime(loadDatetime);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised LimsRecord
     */
    public LimsRecord(dev.ccgcm.platform.orcanexus.jooq.tables.pojos.Lims value) {
        super(Lims.LIMS);

        if (value != null) {
            setSequencingRunId(value.getSequencingRunId());
            setSequencingRunDate(value.getSequencingRunDate());
            setLibraryId(value.getLibraryId());
            setAliasLibraryId(value.getAliasLibraryId());
            setInternalSubjectId(value.getInternalSubjectId());
            setExternalSubjectId(value.getExternalSubjectId());
            setSampleId(value.getSampleId());
            setExternalSampleId(value.getExternalSampleId());
            setExperimentId(value.getExperimentId());
            setProjectId(value.getProjectId());
            setOwnerId(value.getOwnerId());
            setWorkflow(value.getWorkflow());
            setPhenotype(value.getPhenotype());
            setType(value.getType());
            setAssay(value.getAssay());
            setQuality(value.getQuality());
            setSource(value.getSource());
            setTruseqIndex(value.getTruseqIndex());
            setLoadDatetime(value.getLoadDatetime());
            resetTouchedOnNotNull();
        }
    }
}
