/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.records;


import dev.ccgcm.platform.orcanexus.jooq.tables.Vcf;

import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VcfRecord extends TableRecordImpl<VcfRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mart.vcf.portal_run_id</code>.
     */
    public VcfRecord setPortalRunId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.portal_run_id</code>.
     */
    public String getPortalRunId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mart.vcf.cohort_id</code>.
     */
    public VcfRecord setCohortId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.cohort_id</code>.
     */
    public String getCohortId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mart.vcf.bucket</code>.
     */
    public VcfRecord setBucket(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.bucket</code>.
     */
    public String getBucket() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mart.vcf.key</code>.
     */
    public VcfRecord setKey(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.key</code>.
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mart.vcf.library_id</code>.
     */
    public VcfRecord setLibraryId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.library_id</code>.
     */
    public String getLibraryId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mart.vcf.filename</code>.
     */
    public VcfRecord setFilename(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.filename</code>.
     */
    public String getFilename() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mart.vcf.format</code>.
     */
    public VcfRecord setFormat(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.format</code>.
     */
    public String getFormat() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mart.vcf.size</code>.
     */
    public VcfRecord setSize(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.size</code>.
     */
    public Long getSize() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>mart.vcf.storage_class</code>.
     */
    public VcfRecord setStorageClass(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.storage_class</code>.
     */
    public String getStorageClass() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mart.vcf.e_tag</code>.
     */
    public VcfRecord setETag(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.e_tag</code>.
     */
    public String getETag() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mart.vcf.last_modified_date</code>.
     */
    public VcfRecord setLastModifiedDate(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>mart.vcf.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VcfRecord
     */
    public VcfRecord() {
        super(Vcf.VCF);
    }

    /**
     * Create a detached, initialised VcfRecord
     */
    public VcfRecord(String portalRunId, String cohortId, String bucket, String key, String libraryId, String filename, String format, Long size, String storageClass, String eTag, LocalDateTime lastModifiedDate) {
        super(Vcf.VCF);

        setPortalRunId(portalRunId);
        setCohortId(cohortId);
        setBucket(bucket);
        setKey(key);
        setLibraryId(libraryId);
        setFilename(filename);
        setFormat(format);
        setSize(size);
        setStorageClass(storageClass);
        setETag(eTag);
        setLastModifiedDate(lastModifiedDate);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised VcfRecord
     */
    public VcfRecord(dev.ccgcm.platform.orcanexus.jooq.tables.pojos.Vcf value) {
        super(Vcf.VCF);

        if (value != null) {
            setPortalRunId(value.getPortalRunId());
            setCohortId(value.getCohortId());
            setBucket(value.getBucket());
            setKey(value.getKey());
            setLibraryId(value.getLibraryId());
            setFilename(value.getFilename());
            setFormat(value.getFormat());
            setSize(value.getSize());
            setStorageClass(value.getStorageClass());
            setETag(value.getETag());
            setLastModifiedDate(value.getLastModifiedDate());
            resetTouchedOnNotNull();
        }
    }
}
