/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.records;


import dev.ccgcm.platform.orcanexus.jooq.tables.WorkflowCostReport;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowCostReportRecord extends TableRecordImpl<WorkflowCostReportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mart.workflow_cost_report.portal_run_id</code>.
     */
    public WorkflowCostReportRecord setPortalRunId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.portal_run_id</code>.
     */
    public String getPortalRunId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mart.workflow_cost_report.workflow_name</code>.
     */
    public WorkflowCostReportRecord setWorkflowName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.workflow_name</code>.
     */
    public String getWorkflowName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mart.workflow_cost_report.workflow_version</code>.
     */
    public WorkflowCostReportRecord setWorkflowVersion(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.workflow_version</code>.
     */
    public String getWorkflowVersion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mart.workflow_cost_report.workflow_status</code>.
     */
    public WorkflowCostReportRecord setWorkflowStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.workflow_status</code>.
     */
    public String getWorkflowStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mart.workflow_cost_report.total_cost</code>.
     */
    public WorkflowCostReportRecord setTotalCost(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.total_cost</code>.
     */
    public BigDecimal getTotalCost() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>mart.workflow_cost_report.compute_cost</code>.
     */
    public WorkflowCostReportRecord setComputeCost(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.compute_cost</code>.
     */
    public BigDecimal getComputeCost() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>mart.workflow_cost_report.license_cost</code>.
     */
    public WorkflowCostReportRecord setLicenseCost(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.license_cost</code>.
     */
    public BigDecimal getLicenseCost() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>mart.workflow_cost_report.ica_project</code>.
     */
    public WorkflowCostReportRecord setIcaProject(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.ica_project</code>.
     */
    public String getIcaProject() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mart.workflow_cost_report.cost_unit</code>.
     */
    public WorkflowCostReportRecord setCostUnit(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_cost_report.cost_unit</code>.
     */
    public String getCostUnit() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkflowCostReportRecord
     */
    public WorkflowCostReportRecord() {
        super(WorkflowCostReport.WORKFLOW_COST_REPORT);
    }

    /**
     * Create a detached, initialised WorkflowCostReportRecord
     */
    public WorkflowCostReportRecord(String portalRunId, String workflowName, String workflowVersion, String workflowStatus, BigDecimal totalCost, BigDecimal computeCost, BigDecimal licenseCost, String icaProject, String costUnit) {
        super(WorkflowCostReport.WORKFLOW_COST_REPORT);

        setPortalRunId(portalRunId);
        setWorkflowName(workflowName);
        setWorkflowVersion(workflowVersion);
        setWorkflowStatus(workflowStatus);
        setTotalCost(totalCost);
        setComputeCost(computeCost);
        setLicenseCost(licenseCost);
        setIcaProject(icaProject);
        setCostUnit(costUnit);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised WorkflowCostReportRecord
     */
    public WorkflowCostReportRecord(dev.ccgcm.platform.orcanexus.jooq.tables.pojos.WorkflowCostReport value) {
        super(WorkflowCostReport.WORKFLOW_COST_REPORT);

        if (value != null) {
            setPortalRunId(value.getPortalRunId());
            setWorkflowName(value.getWorkflowName());
            setWorkflowVersion(value.getWorkflowVersion());
            setWorkflowStatus(value.getWorkflowStatus());
            setTotalCost(value.getTotalCost());
            setComputeCost(value.getComputeCost());
            setLicenseCost(value.getLicenseCost());
            setIcaProject(value.getIcaProject());
            setCostUnit(value.getCostUnit());
            resetTouchedOnNotNull();
        }
    }
}
