/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.records;


import dev.ccgcm.platform.orcanexus.jooq.tables.Workflow;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowRecord extends TableRecordImpl<WorkflowRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mart.workflow.portal_run_id</code>.
     */
    public WorkflowRecord setPortalRunId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow.portal_run_id</code>.
     */
    public String getPortalRunId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mart.workflow.library_id</code>.
     */
    public WorkflowRecord setLibraryId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow.library_id</code>.
     */
    public String getLibraryId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mart.workflow.workflow_name</code>.
     */
    public WorkflowRecord setWorkflowName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow.workflow_name</code>.
     */
    public String getWorkflowName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mart.workflow.workflow_version</code>.
     */
    public WorkflowRecord setWorkflowVersion(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow.workflow_version</code>.
     */
    public String getWorkflowVersion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mart.workflow.workflow_status</code>.
     */
    public WorkflowRecord setWorkflowStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow.workflow_status</code>.
     */
    public String getWorkflowStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mart.workflow.workflow_start</code>.
     */
    public WorkflowRecord setWorkflowStart(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow.workflow_start</code>.
     */
    public LocalDateTime getWorkflowStart() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>mart.workflow.workflow_end</code>.
     */
    public WorkflowRecord setWorkflowEnd(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow.workflow_end</code>.
     */
    public LocalDateTime getWorkflowEnd() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>mart.workflow.workflow_duration</code>.
     */
    public WorkflowRecord setWorkflowDuration(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow.workflow_duration</code>.
     */
    public BigDecimal getWorkflowDuration() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>mart.workflow.workflow_comment</code>.
     */
    public WorkflowRecord setWorkflowComment(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow.workflow_comment</code>.
     */
    public String getWorkflowComment() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkflowRecord
     */
    public WorkflowRecord() {
        super(Workflow.WORKFLOW);
    }

    /**
     * Create a detached, initialised WorkflowRecord
     */
    public WorkflowRecord(String portalRunId, String libraryId, String workflowName, String workflowVersion, String workflowStatus, LocalDateTime workflowStart, LocalDateTime workflowEnd, BigDecimal workflowDuration, String workflowComment) {
        super(Workflow.WORKFLOW);

        setPortalRunId(portalRunId);
        setLibraryId(libraryId);
        setWorkflowName(workflowName);
        setWorkflowVersion(workflowVersion);
        setWorkflowStatus(workflowStatus);
        setWorkflowStart(workflowStart);
        setWorkflowEnd(workflowEnd);
        setWorkflowDuration(workflowDuration);
        setWorkflowComment(workflowComment);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised WorkflowRecord
     */
    public WorkflowRecord(dev.ccgcm.platform.orcanexus.jooq.tables.pojos.Workflow value) {
        super(Workflow.WORKFLOW);

        if (value != null) {
            setPortalRunId(value.getPortalRunId());
            setLibraryId(value.getLibraryId());
            setWorkflowName(value.getWorkflowName());
            setWorkflowVersion(value.getWorkflowVersion());
            setWorkflowStatus(value.getWorkflowStatus());
            setWorkflowStart(value.getWorkflowStart());
            setWorkflowEnd(value.getWorkflowEnd());
            setWorkflowDuration(value.getWorkflowDuration());
            setWorkflowComment(value.getWorkflowComment());
            resetTouchedOnNotNull();
        }
    }
}
