/*
 * This file is generated by jOOQ.
 */
package dev.ccgcm.platform.orcanexus.jooq.tables.records;


import dev.ccgcm.platform.orcanexus.jooq.tables.WorkflowOutput;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowOutputRecord extends TableRecordImpl<WorkflowOutputRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mart.workflow_output.portal_run_id</code>.
     */
    public WorkflowOutputRecord setPortalRunId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_output.portal_run_id</code>.
     */
    public String getPortalRunId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mart.workflow_output.cohort_id</code>.
     */
    public WorkflowOutputRecord setCohortId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_output.cohort_id</code>.
     */
    public String getCohortId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mart.workflow_output.bucket</code>.
     */
    public WorkflowOutputRecord setBucket(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_output.bucket</code>.
     */
    public String getBucket() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mart.workflow_output.prefix</code>.
     */
    public WorkflowOutputRecord setPrefix(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_output.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mart.workflow_output.key_count</code>.
     */
    public WorkflowOutputRecord setKeyCount(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>mart.workflow_output.key_count</code>.
     */
    public Long getKeyCount() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkflowOutputRecord
     */
    public WorkflowOutputRecord() {
        super(WorkflowOutput.WORKFLOW_OUTPUT);
    }

    /**
     * Create a detached, initialised WorkflowOutputRecord
     */
    public WorkflowOutputRecord(String portalRunId, String cohortId, String bucket, String prefix, Long keyCount) {
        super(WorkflowOutput.WORKFLOW_OUTPUT);

        setPortalRunId(portalRunId);
        setCohortId(cohortId);
        setBucket(bucket);
        setPrefix(prefix);
        setKeyCount(keyCount);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised WorkflowOutputRecord
     */
    public WorkflowOutputRecord(dev.ccgcm.platform.orcanexus.jooq.tables.pojos.WorkflowOutput value) {
        super(WorkflowOutput.WORKFLOW_OUTPUT);

        if (value != null) {
            setPortalRunId(value.getPortalRunId());
            setCohortId(value.getCohortId());
            setBucket(value.getBucket());
            setPrefix(value.getPrefix());
            setKeyCount(value.getKeyCount());
            resetTouchedOnNotNull();
        }
    }
}
